VALID_EMAIL = "user@example.co.il"
VALID_PASSWORD = "ValidPassword1!"
VALID_PHONE_NUMBER = "1234567890"
FIRST_NAME = "John"
LAST_NAME = "Doe"
VALID_BIRTHDAY = "1990-01-01"

SUCCESS_CODE = 200
BAD_REQUEST_CODE = 400
UNAUTHORIZED_CODE = 403
USER_REGISTRATION_SUCCESS_MESSAGE = "User registered successfully"
USER_REGISTRATION_INVALID_EMAIL_MESSAGE = "Invalid email format"
USER_REGISTRATION_INVALID_PASSWORD_MESSAGE = "Password must contain at least one uppercase letter, one lowercase letter and one digit."
USER_REGISTRATION_INVALID_BIRTHDAY_MESSAGE = "Invalid birthday date"
USER_ALREADY_EXISTS_MESSAGE = "already exists"
INCORRECT_CREDENTIALS_LOGIN = "Invalid credentials."
REGISTRATION_FAILED = "Registration failed:"
FUTURE_RIDES_INVALID_INPUT_MESSAGE = ""

# Constants for driver_post_future_rides function
DEFAULT_DEPARTURE_LOCATION = "Location A"
DEFAULT_PICKUP_RADIUS = 5.0
DEFAULT_DESTINATION = "Location B"
DEFAULT_DROP_RADIUS = 5.0
DEFAULT_DEPARTURE_DATETIME = "2024-06-15T15:00:00.000Z"
DEFAULT_AVAILABLE_SEATS = 4
DEFAULT_NOTES = "No notes"


RIDE_POSTED_SUCCESSFULLY = "Ride posted successfully"
DEPARTURE_DATETIME_KEY = "departure_datetime"
