name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUR_EC2_INSTANCE_IP }} << 'EOF'
        cd /home/ubuntu/Backend
        sudo git pull origin master
        source /home/ubuntu/Backend/api-server-flask/venv/bin/activate
        /home/ubuntu/Backend/api-server-flask/venv/bin/pip install -r /home/ubuntu/Backend/api-server-flask/requirements.txt
        sudo systemctl daemon-reload
        sudo systemctl restart carpoolbuddies.service
        EOF
