name: API Flask Server

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m venv env
        # . env/bin/activate
        python -m pip install --upgrade pip
        pip install -r api-server-flask/requirements.txt || echo "No requirements.txt file found"
    - name: Set up Flask environment variables
      env:
        FLASK_APP: run.py
        FLASK_ENV: development
      run: echo "Environment variables set"
    - name: Start Flask server
      env:
        FLASK_APP: run.py
        FLASK_ENV: development
      run: |
        # . env/bin/activate
        cd api-server-flask
        flask run
